#!/bin/bash

# Deployment Commands for Restaurant SaaS
# This script contains all the commands needed to deploy the project

echo "🚀 Restaurant SaaS Deployment Commands"
echo "========================================"
echo ""

# Step 1: Prepare for deployment
echo "Step 1: Prepare for deployment"
echo "------------------------------"
echo "Run these commands locally:"
echo ""
echo "# Build frontend"
echo "npm run build --workspace=frontend"
echo ""
echo "# Build backend"
echo "npm run build --workspace=backend"
echo ""
echo "# Commit changes"
echo "git add ."
echo "git commit -m 'Ready for Vercel deployment'"
echo "git push origin main"
echo ""

# Step 2: Deploy Frontend to Vercel
echo "Step 2: Deploy Frontend to Vercel"
echo "---------------------------------"
echo "1. Go to https://vercel.com/new"
echo "2. Click 'Import Git Repository'"
echo "3. Paste your GitHub repository URL"
echo "4. Configure:"
echo "   - Framework: Vite"
echo "   - Root Directory: frontend"
echo "   - Build Command: npm run build"
echo "   - Output Directory: dist"
echo "5. Click 'Deploy'"
echo ""
echo "After deployment, copy your Vercel URL (e.g., https://restaurant-saas.vercel.app)"
echo ""

# Step 3: Deploy Backend to Railway
echo "Step 3: Deploy Backend to Railway"
echo "--------------------------------"
echo "1. Go to https://railway.app"
echo "2. Click 'New Project'"
echo "3. Select 'Deploy from GitHub'"
echo "4. Choose your repository"
echo "5. Select 'backend' directory"
echo "6. Add services:"
echo "   - PostgreSQL"
echo "   - Redis"
echo "7. Set environment variables:"
echo ""
echo "   # Generate JWT_SECRET"
echo "   openssl rand -base64 32"
echo ""
echo "   # Set these in Railway:"
echo "   JWT_SECRET=<generated-secret>"
echo "   CORS_ORIGINS=https://your-vercel-url.vercel.app"
echo "   NODE_ENV=production"
echo ""
echo "8. Click 'Deploy'"
echo ""
echo "After deployment, copy your Railway URL"
echo ""

# Step 4: Connect Frontend to Backend
echo "Step 4: Connect Frontend to Backend"
echo "-----------------------------------"
echo "1. Go to Vercel dashboard"
echo "2. Select your project"
echo "3. Settings → Environment Variables"
echo "4. Add/Update VITE_API_URL:"
echo "   VITE_API_URL=https://your-railway-url.up.railway.app"
echo "5. Go to Deployments"
echo "6. Click 'Redeploy' on latest deployment"
echo ""

# Step 5: Test
echo "Step 5: Test Your Deployment"
echo "----------------------------"
echo "1. Visit your Vercel URL"
echo "2. Login with:"
echo "   Username: superadmin"
echo "   Password: qwertyuiop"
echo "3. Test menu loading"
echo "4. Test creating orders"
echo ""

# Useful commands
echo "Useful Commands"
echo "==============="
echo ""
echo "# Local development"
echo "npm run dev"
echo ""
echo "# Build all"
echo "npm run build"
echo ""
echo "# Build frontend only"
echo "npm run build --workspace=frontend"
echo ""
echo "# Build backend only"
echo "npm run build --workspace=backend"
echo ""
echo "# Run tests"
echo "npm test"
echo ""
echo "# Generate JWT secret"
echo "openssl rand -base64 32"
echo ""
echo "# Check Node version"
echo "node --version"
echo ""
echo "# Install dependencies"
echo "npm install"
echo ""

# Environment variables
echo "Environment Variables"
echo "====================="
echo ""
echo "Backend (Railway):"
echo "  DATABASE_URL=postgresql://..."
echo "  REDIS_URL=redis://..."
echo "  JWT_SECRET=<your-secret>"
echo "  CORS_ORIGINS=https://your-vercel-url.vercel.app"
echo "  NODE_ENV=production"
echo ""
echo "Frontend (Vercel):"
echo "  VITE_API_URL=https://your-railway-url.up.railway.app"
echo ""

# Troubleshooting
echo "Troubleshooting"
echo "==============="
echo ""
echo "# Check Vercel logs"
echo "vercel logs"
echo ""
echo "# Check Railway logs"
echo "# Go to Railway dashboard → Logs tab"
echo ""
echo "# Redeploy on Vercel"
echo "vercel --prod"
echo ""
echo "# Redeploy on Railway"
echo "# Go to Railway dashboard → Deployments → Redeploy"
echo ""

# Documentation
echo "Documentation"
echo "============="
echo ""
echo "- QUICK_DEPLOY.md - 10-minute deployment guide"
echo "- DEPLOYMENT_GUIDE.md - Comprehensive guide"
echo "- DEPLOYMENT_CHECKLIST.md - Step-by-step checklist"
echo "- VERCEL_DEPLOYMENT_SUMMARY.md - Overview"
echo ""

echo "✅ Deployment setup complete!"
echo ""
echo "Next steps:"
echo "1. Read QUICK_DEPLOY.md for 10-minute deployment"
echo "2. Or follow DEPLOYMENT_GUIDE.md for detailed instructions"
echo "3. Use DEPLOYMENT_CHECKLIST.md to track progress"
