import { create } from 'zustand';
import { persist } from 'zustand/middleware';

type Lang = 'uz' | 'ru' | 'en';

interface LangState {
  lang: Lang;
  setLang: (lang: Lang) => void;
}

const translations: Record<Lang, Record<string, string>> = {
  uz: {
    // Umumiy
    'save': 'Saqlash',
    'cancel': 'Bekor qilish',
    'loading': 'Yuklanmoqda...',
    'settings': 'Sozlamalar',
    'language': 'Til',
    'add': "Qo'shish",
    'edit': 'Tahrirlash',
    'delete': "O'chirish",
    'search': 'Qidirish',
    'refresh': 'Yangilash',
    'close': 'Yopish',
    'yes': 'Ha',
    'no': "Yo'q",
    'back': 'Orqaga',
    'next': 'Keyingi',
    'confirm': 'Tasdiqlash',
    'name': 'Nomi',
    'description': 'Tavsif',
    'price': 'Narx',
    'available': 'Mavjud',
    'unavailable': 'Mavjud emas',
    'active': 'Faol',
    'inactive': 'Nofaol',
    'all': 'Barchasi',
    'no_data': "Ma'lumot yo'q",
    'error': 'Xatolik',
    'success': 'Muvaffaqiyatli',

    // Nav / Header
    'admin_panel': 'Admin Panel',
    'dashboard': 'Dashboard',
    'menu': 'Menyu',
    'categories': 'Kategoriyalar',
    'qr_codes': 'QR Kodlar',
    'profile': 'Profil',
    'logout': 'Chiqish',
    'home': 'Bosh sahifa',
    'scanner': 'Skaner',
    'live_update': 'Jonli Yangilanish',

    // Dashboard
    'welcome': 'Salom',
    'today_status': 'Bugungi holat',
    'tables': 'Stollar',
    'total_revenue': 'Jami Tushum',
    'menu_items': 'Menyu Tanlovi',
    'recent_orders': 'So\'nggi buyurtmalar',
    'view_all': 'Barchasini ko\'rish',
    'quick_links': 'Havolalar',
    'add_menu': 'Menyu qo\'shish',
    'top_items': 'Eng ko\'p sotilgan taomlar',
    'all_orders_stat': 'Barcha buyurtmalar bo\'yicha',
    'sold_count': 'ta',

    // Orders
    'orders': 'Buyurtmalar',
    'order': 'Buyurtma',
    'table': 'Stol',
    'total': 'Jami',
    'status': 'Holat',
    'payment': "To'lov",
    'time': 'Vaqt',
    'actions': 'Amallar',
    'items': 'Ovqatlar',
    'pending': 'Kutilmoqda',
    'confirmed': 'Tasdiqlandi',
    'preparing': 'Tayyorlanmoqda',
    'ready': 'Tayyor',
    'served': 'Berildi',
    'completed': 'Yakunlandi',
    'cancelled': 'Bekor qilindi',
    'cash': 'Naqd pul',
    'card': 'Plastik karta',
    'confirm_order': 'Tasdiqlash',
    'prepare_order': 'Tayyorlash',
    'ready_order': 'Tayyor',
    'serve_order': 'Berish',
    'complete_order': 'Yakunlash',
    'no_orders': 'Hozircha buyurtmalar yo\'q',
    'orders_appear': 'Mijozlar buyurtma berganida bu yerda ko\'rinadi',
    'order_management': 'Jonli navbat boshqaruvi',
    'orders_total': 'Barcha buyurtmalar summasi',
    'completed_total': 'Yakunlangan buyurtmalar summasi',
    'avg_order': 'O\'rtacha buyurtma narxi',

    // Menu
    'add_item': 'Yangi Ovqat',
    'edit_item': 'Ovqatni Tahrirlash',
    'item_name': 'Ovqat nomi',
    'item_desc': 'Tavsif',
    'item_price': 'Narx (so\'m)',
    'category': 'Kategoriya',
    'prep_time': 'Tayyorlanish vaqti (daqiqa)',
    'image': 'Rasm',
    'no_menu': 'Hozircha menyu bo\'sh',
    'add_first_item': 'Birinchi ovqatni qo\'shing',
    'manage_menu': 'Menyu va kategoriyalarni boshqaring',
    'select_category': '— Kategoriyani tanlang —',
    'item_available': 'Mavjud',
    'item_unavailable': 'Mavjud emas',
    'upload_photo': 'Rasm yuklash',
    'change_photo': 'Rasmni o\'zgartirish',
    'remove_photo': 'Rasmni o\'chirish',
    'save_item': 'Saqlash',
    'add_item_btn': 'Qo\'shish',
    'required_fields': '* belgisi bilan belgilangan maydonlar majburiy',

    // Categories
    'add_category': 'Yangi Kategoriya',
    'edit_category': 'Kategoriyani Tahrirlash',
    'category_name': 'Kategoriya nomi',
    'display_order': 'Tartib raqami',
    'no_categories': 'Hozircha kategoriyalar yo\'q',
    'add_first_category': 'Birinchi kategoriyani qo\'shing',
    'manage_categories': 'Menyu kategoriyalarini boshqaring',
    'quick_select': 'Tezkor tanlov',
    'category_settings': 'Kategoriya sozlamalari',

    // QR
    'qr_title': 'QR Kodlar',
    'qr_desc': 'Har bir stol uchun unikal QR kod',
    'download_all': 'Barchasini Yuklab Olish',
    'download': 'Yuklab Olish',
    'generating': 'QR kodlar generatsiya qilinmoqda...',
    'table_num': 'Stol',

    // Settings
    'service_fee': 'Xizmat haqi foizi',
    'service_fee_hint': 'Buyurtma subtotalidan olinadigan foiz',
    'card_qr_image': "Karta QR rasm (to'lov uchun)",
    'card_qr_hint': "Mijoz karta tanlasa, shu rasm ko'rsatiladi",
    'upload_image': 'Rasm yuklash',
    'change_image': "Rasmni o'zgartirish",
    'remove_image': "Rasmni o'chirish",
    'payment_settings': "To'lov sozlamalari",
    'restaurant_settings': 'Restoran sozlamalari',

    // Login
    'login_title': 'Tizimga Kirish',
    'login_subtitle': 'Email yoki telefon raqamingiz bilan kiring',
    'identifier_label': 'Email yoki telefon raqam',
    'identifier_placeholder': 'email@example.com yoki +998901234567',
    'password_label': 'Parol',
    'password_placeholder': 'Parolni kiriting',
    'login_btn': 'Kirish',
    'logging_in': 'Kirish...',
    'no_account': 'Hisobingiz yo\'qmi?',
    'register_link': 'Ro\'yxatdan o\'tish',
    'login_error': 'Email/telefon yoki parol noto\'g\'ri',

    // Register
    'register_title': 'Ro\'yxatdan O\'tish',
    'register_subtitle': 'Email bilan ro\'yxatdan o\'ting',
    'email_label': 'Email',
    'email_placeholder': 'email@example.com',
    'verify_btn': 'Tasdiqlash',
    'verified': 'Tasdiqlandi',
    'password_min': 'Kamida 6 ta belgi',
    'confirm_password': 'Parolni tasdiqlang',
    'confirm_placeholder': 'Qayta kiriting',
    'register_btn': 'Ro\'yxatdan o\'tish',
    'registering': 'Ro\'yxatdan o\'tmoqda...',
    'have_account': 'Allaqachon hisobingiz bormi?',
    'login_link': 'Kirish',
    'back_to_login': 'Kirishga qaytish',

    // Menu
    'menu_title': 'Menyu',
    'search_placeholder': 'Ovqat qidirish...',
    'add_to_cart': 'Qo\'shish',
    'cart_btn': 'Savat',
    'popular': 'Mashhur',
    'min': 'daqiqa',
    'menu_empty': 'Menyu topilmadi',
    'menu_empty_desc': 'Iltimos, keyinroq qayta urinib ko\'ring',
    'back_home': 'Bosh sahifaga qaytish',
    'search_empty': 'topilmadi',
    'search_empty_desc': 'Boshqa so\'z bilan qidiring',
    'clear_search': 'Qidiruvni tozalash',
    'loading_menu': 'Menyu yuklanmoqda...',
    'table_label': 'Stol',

    // OrderTracking
    'order_title': 'Buyurtma',
    'order_not_found': 'Buyurtma topilmadi',
    'order_not_found_desc': 'Ushbu buyurtma mavjud emas yoki o\'chirilgan',
    'back_to_menu': 'Menyuga qaytish',
    'order_process': 'Buyurtma jarayoni',
    'order_items': 'Buyurtma tarkibi',
    'live_tracking': 'Jonli yangilanish',
    'live_tracking_desc': 'Buyurtma holati har 5 soniyada avtomatik yangilanadi',
    'need_help': 'Yordam kerakmi?',
    'need_help_desc': 'Buyurtmangiz bilan bog\'liq savol bo\'lsa, xodimlarimizga murojaat qiling.',
    'cancel_order': 'Buyurtmani bekor qilish',
    'cancel_confirm': 'Buyurtmani bekor qilish',
    'cancel_confirm_desc': 'raqamli buyurtmani bekor qilmoqchimisiz? Bu amalni qaytarib bo\'lmaydi.',
    'cancelling': 'Bekor qilinmoqda...',
    'cancel_yes': 'Ha, bekor qilish',
    'status_pending': 'Kutilmoqda',
    'status_confirmed': 'Tasdiqlandi',
    'status_preparing': 'Tayyorlanmoqda',
    'status_ready': 'Tayyor',
    'status_served': 'Xizmat qilindi',
    'status_completed': 'Yakunlandi',
    'status_cancelled': 'Bekor qilindi',
    'step_pending': 'Buyurtma qabul qilindi',
    'step_confirmed': 'Restoran tomonidan tasdiqlandi',
    'step_preparing': 'Oshpaz tayyorlayapti',
    'step_ready': 'Buyurtma tayyor',
    'step_served': 'Buyurtma xizmat qilindi',
    'now': 'Hozir',

    // SuperAdmin
    'super_admin': 'Super Admin',
    'system_control': 'Tizim boshqaruvi',
    'restaurants': 'Restoranlar',
    'users': 'Foydalanuvchilar',
    'activity': 'Faollik',
    'new_restaurant': 'Yangi Restoran',
    'restaurant_name': 'Restoran nomi',
    'owner_name': 'Egasi',
    'contact': 'Aloqa',
    'login_col': 'Login',
    'no_restaurants': 'Hozircha restoranlar yo\'q',
    'promote': 'Promote',
    'demote': 'Demote',
    'make_admin': 'Admin qilish',
    'permissions': 'Ruxsatlar',
    'super_admin_badge': 'Super Admin',
    'admin_badge': 'Admin',
    'user_badge': 'Foydalanuvchi',

    // CustomerPanel
    'customer_panel': 'Mijoz Paneli',
    'welcome_customer': 'Xush kelibsiz',
    'scan_qr': 'QR Kod Skanerlash',
    'scan_qr_desc': 'Stol QR kodini skanerlang va buyurtma bering',
    'scan_btn': 'QR Skanerlash',
    'restaurants_list': 'Restoranlar',
    'restaurants_desc': 'Barcha mavjud restoranlar ro\'yxati',
    'view_menu_btn': 'Menyuni ko\'rish',
    'no_restaurants_yet': 'Hozircha restoranlar yo\'q',
    'scan_qr_hint': 'QR kodni skanerlang',
    'tables_count': 'ta stol',
  
    'subtotal': 'Subtotal',
    'service_fee_label': 'Xizmat haqi',
    'payment_method': "To'lov usuli",
    'place_order': 'Buyurtma berish',
    'clear_cart': 'Savatni tozalash',
    'cash_desc': "To'lovni xodimga bering",
    'card_desc': "Terminal orqali to'lang",
    'cart_title': 'Savat',
    'cart_empty': 'Savat bo\'sh',
    'cart_empty_desc': 'Hozircha hech narsa tanlamadingiz',
    'view_menu': 'Menyuni ko\'rish',
    'order_list': 'Buyurtma ro\'yxati',
    'order_summary': 'Buyurtma xulasasi',
    'special_request': 'Maxsus talab (ixtiyoriy): kam tuz, o\'tkir emas...',
    'order_info': 'Buyurtma qabul qilingandan so\'ng tayyorlanish jarayonini kuzatishingiz mumkin.',
    'card_qr_scan': 'Karta orqali to\'lash uchun QR kodni skanlang:',
    'placing': 'Berilmoqda...',
  },

  ru: {
    'save': 'Сохранить',
    'cancel': 'Отмена',
    'loading': 'Загрузка...',
    'settings': 'Настройки',
    'language': 'Язык',
    'add': 'Добавить',
    'edit': 'Редактировать',
    'delete': 'Удалить',
    'search': 'Поиск',
    'refresh': 'Обновить',
    'close': 'Закрыть',
    'yes': 'Да',
    'no': 'Нет',
    'back': 'Назад',
    'next': 'Далее',
    'confirm': 'Подтвердить',
    'name': 'Название',
    'description': 'Описание',
    'price': 'Цена',
    'available': 'Доступно',
    'unavailable': 'Недоступно',
    'active': 'Активен',
    'inactive': 'Неактивен',
    'all': 'Все',
    'no_data': 'Нет данных',
    'error': 'Ошибка',
    'success': 'Успешно',

    'admin_panel': 'Панель администратора',
    'dashboard': 'Дашборд',
    'menu': 'Меню',
    'categories': 'Категории',
    'qr_codes': 'QR Коды',
    'profile': 'Профиль',
    'logout': 'Выйти',
    'home': 'Главная',
    'scanner': 'Сканер',
    'live_update': 'Обновление в реальном времени',

    'welcome': 'Привет',
    'today_status': 'Статус сегодня',
    'tables': 'Столы',
    'total_revenue': 'Общая выручка',
    'menu_items': 'Позиции меню',
    'recent_orders': 'Последние заказы',
    'view_all': 'Смотреть все',
    'quick_links': 'Быстрые ссылки',
    'add_menu': 'Добавить в меню',
    'top_items': 'Самые популярные блюда',
    'all_orders_stat': 'По всем заказам',
    'sold_count': 'шт',

    'orders': 'Заказы',
    'order': 'Заказ',
    'table': 'Стол',
    'total': 'Итого',
    'status': 'Статус',
    'payment': 'Оплата',
    'time': 'Время',
    'actions': 'Действия',
    'items': 'Блюда',
    'pending': 'Ожидает',
    'confirmed': 'Подтверждён',
    'preparing': 'Готовится',
    'ready': 'Готов',
    'served': 'Подан',
    'completed': 'Завершён',
    'cancelled': 'Отменён',
    'cash': 'Наличные',
    'card': 'Карта',
    'confirm_order': 'Подтвердить',
    'prepare_order': 'Готовить',
    'ready_order': 'Готов',
    'serve_order': 'Подать',
    'complete_order': 'Завершить',
    'no_orders': 'Заказов пока нет',
    'orders_appear': 'Заказы появятся здесь когда клиенты сделают заказ',
    'order_management': 'Управление очередью в реальном времени',
    'orders_total': 'Сумма всех заказов',
    'completed_total': 'Сумма завершённых заказов',
    'avg_order': 'Средняя стоимость заказа',

    'add_item': 'Новое блюдо',
    'edit_item': 'Редактировать блюдо',
    'item_name': 'Название блюда',
    'item_desc': 'Описание',
    'item_price': 'Цена (сум)',
    'category': 'Категория',
    'prep_time': 'Время приготовления (мин)',
    'image': 'Изображение',
    'no_menu': 'Меню пока пустое',
    'add_first_item': 'Добавьте первое блюдо',
    'manage_menu': 'Управляйте меню и категориями',
    'select_category': '— Выберите категорию —',
    'item_available': 'Доступно',
    'item_unavailable': 'Недоступно',
    'upload_photo': 'Загрузить фото',
    'change_photo': 'Изменить фото',
    'remove_photo': 'Удалить фото',
    'save_item': 'Сохранить',
    'add_item_btn': 'Добавить',
    'required_fields': 'Поля отмеченные * обязательны',

    'add_category': 'Новая категория',
    'edit_category': 'Редактировать категорию',
    'category_name': 'Название категории',
    'display_order': 'Порядок отображения',
    'no_categories': 'Категорий пока нет',
    'add_first_category': 'Добавьте первую категорию',
    'manage_categories': 'Управляйте категориями меню',
    'quick_select': 'Быстрый выбор',
    'category_settings': 'Настройки категории',

    'qr_title': 'QR Коды',
    'qr_desc': 'Уникальный QR код для каждого стола',
    'download_all': 'Скачать все',
    'download': 'Скачать',
    'generating': 'Генерация QR кодов...',
    'table_num': 'Стол',

    'service_fee': 'Процент сервисного сбора',
    'service_fee_hint': 'Процент от суммы заказа',
    'card_qr_image': 'QR для оплаты картой',
    'card_qr_hint': 'Показывается клиенту при выборе оплаты картой',
    'upload_image': 'Загрузить изображение',
    'change_image': 'Изменить изображение',
    'remove_image': 'Удалить изображение',
    'payment_settings': 'Настройки оплаты',
    'restaurant_settings': 'Настройки ресторана',

    // Login
    'login_title': 'Вход в систему',
    'login_subtitle': 'Войдите с помощью email или телефона',
    'identifier_label': 'Email или номер телефона',
    'identifier_placeholder': 'email@example.com или +998901234567',
    'password_label': 'Пароль',
    'password_placeholder': 'Введите пароль',
    'login_btn': 'Войти',
    'logging_in': 'Вход...',
    'no_account': 'Нет аккаунта?',
    'register_link': 'Зарегистрироваться',
    'login_error': 'Неверный email/телефон или пароль',
    'register_title': 'Регистрация',
    'register_subtitle': 'Зарегистрируйтесь с помощью email',
    'email_label': 'Email',
    'email_placeholder': 'email@example.com',
    'verify_btn': 'Подтвердить',
    'verified': 'Подтверждён',
    'password_min': 'Минимум 6 символов',
    'confirm_password': 'Подтвердите пароль',
    'confirm_placeholder': 'Введите ещё раз',
    'register_btn': 'Зарегистрироваться',
    'registering': 'Регистрация...',
    'have_account': 'Уже есть аккаунт?',
    'login_link': 'Войти',
    'back_to_login': 'Вернуться к входу',
    'menu_title': 'Меню',
    'search_placeholder': 'Поиск блюд...',
    'add_to_cart': 'Добавить',
    'cart_btn': 'Корзина',
    'popular': 'Популярное',
    'min': 'мин',
    'menu_empty': 'Меню не найдено',
    'menu_empty_desc': 'Пожалуйста, попробуйте позже',
    'back_home': 'На главную',
    'search_empty': 'не найдено',
    'search_empty_desc': 'Попробуйте другое слово',
    'clear_search': 'Очистить поиск',
    'loading_menu': 'Загрузка меню...',
    'table_label': 'Стол',
    'order_title': 'Заказ',
    'order_not_found': 'Заказ не найден',
    'order_not_found_desc': 'Этот заказ не существует или был удалён',
    'back_to_menu': 'Вернуться в меню',
    'order_process': 'Процесс заказа',
    'order_items': 'Состав заказа',
    'live_tracking': 'Обновление в реальном времени',
    'live_tracking_desc': 'Статус заказа обновляется каждые 5 секунд',
    'need_help': 'Нужна помощь?',
    'need_help_desc': 'Если у вас есть вопросы по заказу, обратитесь к персоналу.',
    'cancel_order': 'Отменить заказ',
    'cancel_confirm': 'Отмена заказа',
    'cancel_confirm_desc': 'Вы хотите отменить заказ? Это действие нельзя отменить.',
    'cancelling': 'Отменяется...',
    'cancel_yes': 'Да, отменить',
    'status_pending': 'Ожидает',
    'status_confirmed': 'Подтверждён',
    'status_preparing': 'Готовится',
    'status_ready': 'Готов',
    'status_served': 'Подан',
    'status_completed': 'Завершён',
    'status_cancelled': 'Отменён',
    'step_pending': 'Заказ принят',
    'step_confirmed': 'Подтверждён рестораном',
    'step_preparing': 'Повар готовит',
    'step_ready': 'Заказ готов',
    'step_served': 'Заказ подан',
    'now': 'Сейчас',
    'super_admin': 'Супер Админ',
    'system_control': 'Управление системой',
    'restaurants': 'Рестораны',
    'users': 'Пользователи',
    'activity': 'Активность',
    'new_restaurant': 'Новый ресторан',
    'restaurant_name': 'Название ресторана',
    'owner_name': 'Владелец',
    'contact': 'Контакт',
    'login_col': 'Логин',
    'no_restaurants': 'Ресторанов пока нет',
    'promote': 'Повысить',
    'demote': 'Понизить',
    'make_admin': 'Сделать админом',
    'permissions': 'Права',
    'super_admin_badge': 'Супер Админ',
    'admin_badge': 'Админ',
    'user_badge': 'Пользователь',
    'customer_panel': 'Панель клиента',
    'welcome_customer': 'Добро пожаловать',
    'scan_qr': 'Сканирование QR',
    'scan_qr_desc': 'Отсканируйте QR код стола и сделайте заказ',
    'scan_btn': 'Сканировать QR',
    'restaurants_list': 'Рестораны',
    'restaurants_desc': 'Список всех доступных ресторанов',
    'view_menu_btn': 'Смотреть меню',
    'no_restaurants_yet': 'Ресторанов пока нет',
    'scan_qr_hint': 'Отсканируйте QR код',
    'tables_count': 'столов',

    'order_placed': 'Заказ успешно оформлен!',
    'subtotal': 'Подытог',
    'service_fee_label': 'Сервисный сбор',
    'payment_method': 'Способ оплаты',
    'place_order': 'Оформить заказ',
    'clear_cart': 'Очистить корзину',
    'cash_desc': 'Отдайте деньги сотруднику',
    'card_desc': 'Оплатите через терминал',
    'cart_title': 'Корзина',
    'cart_empty': 'Корзина пуста',
    'cart_empty_desc': 'Вы ничего не выбрали',
    'view_menu': 'Смотреть меню',
    'order_list': 'Список заказа',
    'order_summary': 'Итог заказа',
    'special_request': 'Особые пожелания (необязательно): меньше соли...',
    'order_info': 'После подтверждения заказа вы можете отслеживать его статус.',
    'card_qr_scan': 'Отсканируйте QR для оплаты картой:',
    'placing': 'Оформляется...',
  },

  en: {
    'save': 'Save',
    'cancel': 'Cancel',
    'loading': 'Loading...',
    'settings': 'Settings',
    'language': 'Language',
    'add': 'Add',
    'edit': 'Edit',
    'delete': 'Delete',
    'search': 'Search',
    'refresh': 'Refresh',
    'close': 'Close',
    'yes': 'Yes',
    'no': 'No',
    'back': 'Back',
    'next': 'Next',
    'confirm': 'Confirm',
    'name': 'Name',
    'description': 'Description',
    'price': 'Price',
    'available': 'Available',
    'unavailable': 'Unavailable',
    'active': 'Active',
    'inactive': 'Inactive',
    'all': 'All',
    'no_data': 'No data',
    'error': 'Error',
    'success': 'Success',

    'admin_panel': 'Admin Panel',
    'dashboard': 'Dashboard',
    'menu': 'Menu',
    'categories': 'Categories',
    'qr_codes': 'QR Codes',
    'profile': 'Profile',
    'logout': 'Logout',
    'home': 'Home',
    'scanner': 'Scanner',
    'live_update': 'Live Update',

    'welcome': 'Hello',
    'today_status': 'Today\'s status',
    'tables': 'Tables',
    'total_revenue': 'Total Revenue',
    'menu_items': 'Menu Items',
    'recent_orders': 'Recent Orders',
    'view_all': 'View all',
    'quick_links': 'Quick Links',
    'add_menu': 'Add to menu',
    'top_items': 'Top selling items',
    'all_orders_stat': 'Across all orders',
    'sold_count': 'pcs',

    'orders': 'Orders',
    'order': 'Order',
    'table': 'Table',
    'total': 'Total',
    'status': 'Status',
    'payment': 'Payment',
    'time': 'Time',
    'actions': 'Actions',
    'items': 'Items',
    'pending': 'Pending',
    'confirmed': 'Confirmed',
    'preparing': 'Preparing',
    'ready': 'Ready',
    'served': 'Served',
    'completed': 'Completed',
    'cancelled': 'Cancelled',
    'cash': 'Cash',
    'card': 'Card',
    'confirm_order': 'Confirm',
    'prepare_order': 'Prepare',
    'ready_order': 'Ready',
    'serve_order': 'Serve',
    'complete_order': 'Complete',
    'cancel_order': 'Cancel',
    'no_orders': 'No orders yet',
    'orders_appear': 'Orders will appear here when customers place them',
    'order_management': 'Live queue management',
    'orders_total': 'Total orders amount',
    'completed_total': 'Completed orders amount',
    'avg_order': 'Average order value',

    'add_item': 'New Item',
    'edit_item': 'Edit Item',
    'item_name': 'Item name',
    'item_desc': 'Description',
    'item_price': 'Price (sum)',
    'category': 'Category',
    'prep_time': 'Preparation time (min)',
    'image': 'Image',
    'no_menu': 'Menu is empty',
    'add_first_item': 'Add your first item',
    'manage_menu': 'Manage menu and categories',
    'select_category': '— Select category —',
    'item_available': 'Available',
    'item_unavailable': 'Unavailable',
    'upload_photo': 'Upload photo',
    'change_photo': 'Change photo',
    'remove_photo': 'Remove photo',
    'save_item': 'Save',
    'add_item_btn': 'Add',
    'required_fields': 'Fields marked with * are required',

    'add_category': 'New Category',
    'edit_category': 'Edit Category',
    'category_name': 'Category name',
    'display_order': 'Display order',
    'no_categories': 'No categories yet',
    'add_first_category': 'Add your first category',
    'manage_categories': 'Manage menu categories',
    'quick_select': 'Quick select',
    'category_settings': 'Category settings',

    'qr_title': 'QR Codes',
    'qr_desc': 'Unique QR code for each table',
    'download_all': 'Download All',
    'download': 'Download',
    'generating': 'Generating QR codes...',
    'table_num': 'Table',

    'service_fee': 'Service fee percent',
    'service_fee_hint': 'Percentage of order subtotal',
    'card_qr_image': 'Card QR image (for payment)',
    'card_qr_hint': 'Shown to customer when card payment is selected',
    'upload_image': 'Upload image',
    'change_image': 'Change image',
    'remove_image': 'Remove image',
    'payment_settings': 'Payment settings',
    'restaurant_settings': 'Restaurant settings',

    'login_title': 'Sign In',
    'login_subtitle': 'Sign in with your email or phone',
    'identifier_label': 'Email or phone number',
    'identifier_placeholder': 'email@example.com or +998901234567',
    'password_label': 'Password',
    'password_placeholder': 'Enter password',
    'login_btn': 'Sign In',
    'logging_in': 'Signing in...',
    'no_account': 'Don\'t have an account?',
    'register_link': 'Sign up',
    'login_error': 'Invalid email/phone or password',
    'register_title': 'Sign Up',
    'register_subtitle': 'Register with your email',
    'email_label': 'Email',
    'email_placeholder': 'email@example.com',
    'verify_btn': 'Verify',
    'verified': 'Verified',
    'password_min': 'At least 6 characters',
    'confirm_password': 'Confirm password',
    'confirm_placeholder': 'Enter again',
    'register_btn': 'Sign Up',
    'registering': 'Signing up...',
    'have_account': 'Already have an account?',
    'login_link': 'Sign in',
    'back_to_login': 'Back to login',
    'menu_title': 'Menu',
    'search_placeholder': 'Search food...',
    'add_to_cart': 'Add',
    'cart_btn': 'Cart',
    'popular': 'Popular',
    'min': 'min',
    'menu_empty': 'Menu not found',
    'menu_empty_desc': 'Please try again later',
    'back_home': 'Back to home',
    'search_empty': 'not found',
    'search_empty_desc': 'Try another word',
    'clear_search': 'Clear search',
    'loading_menu': 'Loading menu...',
    'table_label': 'Table',
    'order_title': 'Order',
    'order_not_found': 'Order not found',
    'order_not_found_desc': 'This order does not exist or was deleted',
    'back_to_menu': 'Back to menu',
    'order_process': 'Order process',
    'order_items': 'Order items',
    'live_tracking': 'Live update',
    'live_tracking_desc': 'Order status updates every 5 seconds automatically',
    'need_help': 'Need help?',
    'need_help_desc': 'If you have questions about your order, contact our staff.',
    'cancel_confirm': 'Cancel order',
    'cancel_confirm_desc': 'Do you want to cancel this order? This action cannot be undone.',
    'cancelling': 'Cancelling...',
    'cancel_yes': 'Yes, cancel',
    'status_pending': 'Pending',
    'status_confirmed': 'Confirmed',
    'status_preparing': 'Preparing',
    'status_ready': 'Ready',
    'status_served': 'Served',
    'status_completed': 'Completed',
    'status_cancelled': 'Cancelled',
    'step_pending': 'Order received',
    'step_confirmed': 'Confirmed by restaurant',
    'step_preparing': 'Chef is preparing',
    'step_ready': 'Order is ready',
    'step_served': 'Order served',
    'now': 'Now',
    'super_admin': 'Super Admin',
    'system_control': 'System management',
    'restaurants': 'Restaurants',
    'users': 'Users',
    'activity': 'Activity',
    'new_restaurant': 'New Restaurant',
    'restaurant_name': 'Restaurant name',
    'owner_name': 'Owner',
    'contact': 'Contact',
    'login_col': 'Login',
    'no_restaurants': 'No restaurants yet',
    'promote': 'Promote',
    'demote': 'Demote',
    'make_admin': 'Make admin',
    'permissions': 'Permissions',
    'super_admin_badge': 'Super Admin',
    'admin_badge': 'Admin',
    'user_badge': 'User',
    'customer_panel': 'Customer Panel',
    'welcome_customer': 'Welcome',
    'scan_qr': 'QR Code Scan',
    'scan_qr_desc': 'Scan the table QR code and place an order',
    'scan_btn': 'Scan QR',
    'restaurants_list': 'Restaurants',
    'restaurants_desc': 'List of all available restaurants',
    'view_menu_btn': 'View menu',
    'no_restaurants_yet': 'No restaurants yet',
    'scan_qr_hint': 'Scan QR code',
    'tables_count': 'tables',

    'order_placed': 'Order placed successfully!',
    'subtotal': 'Subtotal',
    'service_fee_label': 'Service fee',
    'payment_method': 'Payment method',
    'place_order': 'Place order',
    'clear_cart': 'Clear cart',
    'cash_desc': 'Pay to the staff',
    'card_desc': 'Pay via terminal',
    'cart_title': 'Cart',
    'cart_empty': 'Cart is empty',
    'cart_empty_desc': 'You haven\'t selected anything yet',
    'view_menu': 'View menu',
    'order_list': 'Order list',
    'order_summary': 'Order summary',
    'special_request': 'Special request (optional): less salt...',
    'order_info': 'After order is confirmed you can track its status.',
    'card_qr_scan': 'Scan QR to pay by card:',
    'placing': 'Placing...',
  },
};

export const useLangStore = create<LangState>()(
  persist(
    (set) => ({
      lang: 'uz',
      setLang: (lang) => set({ lang }),
    }),
    { name: 'lang-storage' }
  )
);

export { translations };

export function useT(): (key: string) => string {
  const lang = useLangStore((state) => state.lang);
  return (key: string) => translations[lang]?.[key] || translations['uz']?.[key] || key;
}

// ── Extra translations injected ──────────────────────────────────────────
// These are appended because the main translations object is already closed.
// useT() will fall back to uz if key not found, so we patch translations directly.

const extraTranslations: Record<'uz' | 'ru' | 'en', Record<string, string>> = {
  uz: {
    'hero_badge': 'Professional restoran boshqaruv tizimi',
    'hero_title1': 'Restoraningizni',
    'hero_title2': 'raqamlashtiring',
    'hero_desc': "QR kod orqali buyurtma, real-time boshqaruv va professional analitika. Mijozlar uchun qulay, adminlar uchun kuchli.",
    'footer_desc': "Professional restoran boshqaruvi va QR kod orqali tezkor buyurtma tizimi. O'zbekiston uchun yaratilgan.",
    'footer_links': 'Havolalar',
    'footer_contact': 'Aloqa',
    'footer_location': "Toshkent, O'zbekiston",
    'footer_rights': '© 2026 Restaurant QR. Barcha huquqlar himoyalangan.',
    'footer_status': 'Barcha tizimlar ishlayapti',
    'scanner_link': 'QR Skanerlash',
    'register_link2': "Ro'yxatdan o'tish",
    'login_link2': 'Kirish',
    'email_verified': 'Email tasdiqlandi',
    'email_already_exists': "Bu email allaqachon ro'yxatdan o'tgan",
    'register_success': "Ro'yxatdan o'tish muvaffaqiyatli!",
    'error_occurred': 'Xatolik yuz berdi',
    'saved': 'Saqlandi',
    'updated': 'Yangilandi',
    'added': "Qo'shildi",
    'saving': 'Saqlanmoqda...',
    'refreshing': 'Yangilanmoqda...',
    'order_status_updated': "Buyurtma holati o'zgartirildi",
    'order_cancelled_success': 'Buyurtma bekor qilindi',
    'cancel_error': 'Bekor qilishda xatolik',
    'item_added_to_cart': "savatga qo'shildi",
    'fill_required': "Barcha majburiy maydonlarni to'ldiring",
    'price_positive': 'Narx 0 dan katta bo\'lishi kerak',
    'image_size_error': 'Rasm hajmi 5MB dan kichik bo\'lishi kerak',
    'image_type_error': 'Faqat rasm fayllari qabul qilinadi',
    'menu_load_error': 'Menyu yuklashda xatolik',
    'login_required': 'Login majburiy',
    'login_format_error': "Login faqat lotin harflari, raqamlar va _ bo'lishi kerak",
    'password_length_error': 'Parol kamida 6 ta belgi bo\'lishi kerak',
    'login_taken': 'Bu login band',
    'email_required': 'Email kiritilmadi',
    'email_invalid': "Email noto'g'ri formatda",
    'email_not_verified': 'Email tasdiqlanmagan',
    'password_required': 'Parol kiritilmadi',
    'passwords_not_match': 'Parollar mos kelmaydi',
    'try_again': "Qaytadan urinib ko'ring",
    'show': "Ko'rsat",
    'hide': 'Yashir',
    'print': 'Chop etish',
    'receipt': 'Chek',
    'receipt_title': 'Buyurtma cheki',
    'get_receipt': 'Chek olish',
    'logout_btn': 'Tizimdan chiqish',
    'profile_settings': 'Profil Sozlamalari',
    'info_tab': "Ma'lumotlar",
    'password_tab': 'Parol',
    'interface_lang': 'Interfeys tili',
    'dine_in': 'Shu yerda',
    'dine_in_desc': 'Issiq holda',
    'takeaway': 'Olib ketish',
    'takeaway_desc': 'Paketda',
    'scroll_down': 'Pastga aylantiring',
    'features_badge': 'Imkoniyatlar',
    'features_title': 'Biznes uchun zarur barcha vositalar',
    'features_desc': 'Bir platformada restoran boshqaruvining barcha jihatlari',
    'how_it_works_badge': 'Qanday ishlaydi',
    'how_it_works_title': '4 ta qadam',
    'how_it_works_desc': 'Oddiy va tezkor buyurtma jarayoni',
    'cta_badge': 'Bugun boshlang',
    'cta_title': "Restoraningizni kelajakka olib chiqing",
    'cta_desc': "Professional buyurtma tizimi bilan biznesingizni rivojlantiring. Bepul sinab ko'ring.",
    'demo_menu': 'Demo Menyu',
    'demo_admin': 'Demo Admin',
    'app_tagline': 'Professional tizim',
    'stat_uptime': 'Uptime',
    'stat_response': 'Javob vaqti',
    'stat_orders': 'Buyurtmalar',
    'stat_langs': 'Til',
    'feat1_title': 'QR Kod Tizimi',
    'feat1_desc': "Har bir stol uchun unikal QR kod. Mijoz skanerlaydi va buyurtma beradi — hech qanday app kerak emas.",
    'feat2_title': 'Real-time Buyurtmalar',
    'feat2_desc': "Admin panelida buyurtmalar real vaqtda yangilanadi. Holat o'zgartirish bir tugma bilan.",
    'feat3_title': 'Analitika va Hisobot',
    'feat3_desc': 'Kunlik daromad, buyurtmalar statistikasi va restoran faoliyatini kuzatib boring.',
    'feat4_title': 'Xavfsiz va Ishonchli',
    'feat4_desc': "JWT autentifikatsiya, rate limiting va ma'lumotlar shifrlash bilan himoyalangan.",
    'feat5_title': "Naqd va Karta To'lov",
    'feat5_desc': "Mijoz naqd yoki plastik karta orqali to'lash imkoniyatiga ega. QR kod orqali to'lov.",
    'feat6_title': "Ko'p Tilli Interfeys",
    'feat6_desc': "O'zbek, Rus va Ingliz tillarida ishlaydi. Admin o'zi tilni tanlaydi.",
    'step1_title': 'QR Skanerlash',
    'step1_desc': 'Stolda joylashgan QR kodni telefon kamerasi bilan skanerlang',
    'step2_title': "Menyu Ko'rish",
    'step2_desc': "Barcha taomlarni ko'ring, narxlarni solishtiring va tanlang",
    'step3_title': 'Buyurtma Berish',
    'step3_desc': "Savatga qo'shing, to'lov usulini tanlang va tasdiqlang",
    'step4_title': 'Kuzatish',
    'step4_desc': 'Buyurtmangiz holatini real vaqtda kuzatib boring',
  },
  ru: {
    'hero_badge': 'Профессиональная система управления рестораном',
    'hero_title1': 'Оцифруйте',
    'hero_title2': 'ваш ресторан',
    'hero_desc': 'Заказы через QR код, управление в реальном времени и профессиональная аналитика. Удобно для клиентов, мощно для администраторов.',
    'footer_desc': 'Профессиональное управление рестораном и быстрая система заказов через QR код. Создано для Узбекистана.',
    'footer_links': 'Ссылки',
    'footer_contact': 'Контакты',
    'footer_location': 'Ташкент, Узбекистан',
    'footer_rights': '© 2026 Restaurant QR. Все права защищены.',
    'footer_status': 'Все системы работают',
    'scanner_link': 'QR Сканер',
    'register_link2': 'Регистрация',
    'login_link2': 'Войти',
    'email_verified': 'Email подтверждён',
    'email_already_exists': 'Этот email уже зарегистрирован',
    'register_success': 'Регистрация прошла успешно!',
    'error_occurred': 'Произошла ошибка',
    'saved': 'Сохранено',
    'updated': 'Обновлено',
    'added': 'Добавлено',
    'saving': 'Сохраняется...',
    'refreshing': 'Обновляется...',
    'order_status_updated': 'Статус заказа изменён',
    'order_cancelled_success': 'Заказ отменён',
    'cancel_error': 'Ошибка при отмене',
    'item_added_to_cart': 'добавлено в корзину',
    'fill_required': 'Заполните все обязательные поля',
    'price_positive': 'Цена должна быть больше 0',
    'image_size_error': 'Размер изображения должен быть меньше 5MB',
    'image_type_error': 'Принимаются только файлы изображений',
    'menu_load_error': 'Ошибка загрузки меню',
    'login_required': 'Логин обязателен',
    'login_format_error': 'Логин может содержать только латинские буквы, цифры и _',
    'password_length_error': 'Пароль должен содержать минимум 6 символов',
    'login_taken': 'Этот логин занят',
    'email_required': 'Email не введён',
    'email_invalid': 'Неверный формат email',
    'email_not_verified': 'Email не подтверждён',
    'password_required': 'Пароль не введён',
    'passwords_not_match': 'Пароли не совпадают',
    'try_again': 'Попробуйте ещё раз',
    'show': 'Показать',
    'hide': 'Скрыть',
    'print': 'Распечатать',
    'receipt': 'Чек',
    'receipt_title': 'Чек заказа',
    'get_receipt': 'Получить чек',
    'logout_btn': 'Выйти из системы',
    'profile_settings': 'Настройки профиля',
    'info_tab': 'Данные',
    'password_tab': 'Пароль',
    'interface_lang': 'Язык интерфейса',
    'dine_in': 'Здесь',
    'dine_in_desc': 'Горячее',
    'takeaway': 'С собой',
    'takeaway_desc': 'В упаковке',
    'scroll_down': 'Прокрутите вниз',
    'features_badge': 'Возможности',
    'features_title': 'Все инструменты для бизнеса',
    'features_desc': 'Все аспекты управления рестораном на одной платформе',
    'how_it_works_badge': 'Как это работает',
    'how_it_works_title': '4 шага',
    'how_it_works_desc': 'Простой и быстрый процесс заказа',
    'cta_badge': 'Начните сегодня',
    'cta_title': 'Выведите ресторан в будущее',
    'cta_desc': 'Развивайте бизнес с профессиональной системой заказов. Попробуйте бесплатно.',
    'demo_menu': 'Демо Меню',
    'demo_admin': 'Демо Админ',
    'app_tagline': 'Профессиональная система',
    'stat_uptime': 'Аптайм',
    'stat_response': 'Время ответа',
    'stat_orders': 'Заказы',
    'stat_langs': 'Языка',
    'feat1_title': 'Система QR Кодов',
    'feat1_desc': 'Уникальный QR код для каждого стола. Клиент сканирует и делает заказ — никакого приложения не нужно.',
    'feat2_title': 'Заказы в реальном времени',
    'feat2_desc': 'Заказы в панели администратора обновляются в реальном времени. Изменение статуса одной кнопкой.',
    'feat3_title': 'Аналитика и отчёты',
    'feat3_desc': 'Отслеживайте дневной доход, статистику заказов и активность ресторана.',
    'feat4_title': 'Безопасно и надёжно',
    'feat4_desc': 'Защищено JWT аутентификацией, ограничением запросов и шифрованием данных.',
    'feat5_title': 'Наличные и карта',
    'feat5_desc': 'Клиент может оплатить наличными или картой. Оплата через QR код.',
    'feat6_title': 'Многоязычный интерфейс',
    'feat6_desc': 'Работает на узбекском, русском и английском языках. Администратор выбирает язык.',
    'step1_title': 'Сканирование QR',
    'step1_desc': 'Отсканируйте QR код на столе камерой телефона',
    'step2_title': 'Просмотр меню',
    'step2_desc': 'Просматривайте блюда, сравнивайте цены и выбирайте',
    'step3_title': 'Оформление заказа',
    'step3_desc': 'Добавьте в корзину, выберите способ оплаты и подтвердите',
    'step4_title': 'Отслеживание',
    'step4_desc': 'Отслеживайте статус заказа в реальном времени',
  },
  en: {
    'hero_badge': 'Professional restaurant management system',
    'hero_title1': 'Digitize',
    'hero_title2': 'your restaurant',
    'hero_desc': 'QR code ordering, real-time management and professional analytics. Easy for customers, powerful for admins.',
    'footer_desc': 'Professional restaurant management and fast QR code ordering system. Built for Uzbekistan.',
    'footer_links': 'Links',
    'footer_contact': 'Contact',
    'footer_location': 'Tashkent, Uzbekistan',
    'footer_rights': '© 2026 Restaurant QR. All rights reserved.',
    'footer_status': 'All systems operational',
    'scanner_link': 'QR Scanner',
    'register_link2': 'Sign Up',
    'login_link2': 'Sign In',
    'email_verified': 'Email verified',
    'email_already_exists': 'This email is already registered',
    'register_success': 'Registration successful!',
    'error_occurred': 'An error occurred',
    'saved': 'Saved',
    'updated': 'Updated',
    'added': 'Added',
    'saving': 'Saving...',
    'refreshing': 'Refreshing...',
    'order_status_updated': 'Order status updated',
    'order_cancelled_success': 'Order cancelled',
    'cancel_error': 'Error cancelling order',
    'item_added_to_cart': 'added to cart',
    'fill_required': 'Please fill in all required fields',
    'price_positive': 'Price must be greater than 0',
    'image_size_error': 'Image size must be less than 5MB',
    'image_type_error': 'Only image files are accepted',
    'menu_load_error': 'Error loading menu',
    'login_required': 'Login is required',
    'login_format_error': 'Login can only contain latin letters, numbers and _',
    'password_length_error': 'Password must be at least 6 characters',
    'login_taken': 'This login is taken',
    'email_required': 'Email is required',
    'email_invalid': 'Invalid email format',
    'email_not_verified': 'Email not verified',
    'password_required': 'Password is required',
    'passwords_not_match': 'Passwords do not match',
    'try_again': 'Please try again',
    'show': 'Show',
    'hide': 'Hide',
    'print': 'Print',
    'receipt': 'Receipt',
    'receipt_title': 'Order Receipt',
    'get_receipt': 'Get Receipt',
    'logout_btn': 'Sign Out',
    'profile_settings': 'Profile Settings',
    'info_tab': 'Info',
    'password_tab': 'Password',
    'interface_lang': 'Interface language',
    'dine_in': 'Dine In',
    'dine_in_desc': 'Hot & fresh',
    'takeaway': 'Takeaway',
    'takeaway_desc': 'Packaged',
    'scroll_down': 'Scroll down',
    'features_badge': 'Features',
    'features_title': 'All tools your business needs',
    'features_desc': 'Every aspect of restaurant management on one platform',
    'how_it_works_badge': 'How it works',
    'how_it_works_title': '4 steps',
    'how_it_works_desc': 'Simple and fast ordering process',
    'cta_badge': 'Get started today',
    'cta_title': 'Take your restaurant into the future',
    'cta_desc': 'Grow your business with a professional ordering system. Try it free.',
    'demo_menu': 'Demo Menu',
    'demo_admin': 'Demo Admin',
    'app_tagline': 'Professional system',
    'stat_uptime': 'Uptime',
    'stat_response': 'Response time',
    'stat_orders': 'Orders',
    'stat_langs': 'Languages',
    'feat1_title': 'QR Code System',
    'feat1_desc': 'Unique QR code for each table. Customer scans and orders — no app needed.',
    'feat2_title': 'Real-time Orders',
    'feat2_desc': 'Orders update in real time in the admin panel. Change status with one button.',
    'feat3_title': 'Analytics & Reports',
    'feat3_desc': 'Track daily revenue, order statistics and restaurant activity.',
    'feat4_title': 'Secure & Reliable',
    'feat4_desc': 'Protected with JWT authentication, rate limiting and data encryption.',
    'feat5_title': 'Cash & Card Payment',
    'feat5_desc': 'Customer can pay with cash or card. Payment via QR code.',
    'feat6_title': 'Multilingual Interface',
    'feat6_desc': 'Works in Uzbek, Russian and English. Admin chooses the language.',
    'step1_title': 'Scan QR',
    'step1_desc': 'Scan the QR code on the table with your phone camera',
    'step2_title': 'View Menu',
    'step2_desc': 'Browse dishes, compare prices and choose',
    'step3_title': 'Place Order',
    'step3_desc': 'Add to cart, choose payment method and confirm',
    'step4_title': 'Track',
    'step4_desc': 'Track your order status in real time',
  },
};

// Patch translations with extra keys
Object.keys(extraTranslations).forEach((lang) => {
  const l = lang as 'uz' | 'ru' | 'en';
  Object.assign(translations[l], extraTranslations[l]);
});

// ── Admin & SuperAdmin extra translations ────────────────────────────────
const adminTranslations: Record<'uz' | 'ru' | 'en', Record<string, string>> = {
  uz: {
    'refreshing_btn': 'Yangilanmoqda...',
    'refresh_btn': 'Yangilash',
    'saving_btn': 'Saqlanmoqda...',
    'save_btn': 'Saqlash',
    'submitting': 'Yuborilmoqda...',
    'cancel_btn': 'Bekor qilish',
    'add_btn': "Qo'shish",
    'edit_btn': 'Tahrirlash',
    'delete_btn': "O'chirish",
    'new_orders_badge': 'ta yangi buyurtma',
    'live_data': "Jonli ma'lumot",
    'pending_status': 'Navbatda',
    'table_prefix': 'Stol',
    'som': "so'm",
    'minute_short': 'daqiqa',
    'scanner_btn': 'Skaner',
    'system_control': 'Tizim boshqaruvi',
    'total_active': 'Jami faol',
    'admins_count': 'Adminlar',
    'last_7_days': "So'nggi 7 kun — Zakazlar",
    'new_restaurant_btn': 'Yangi Restoran',
    'edit_btn2': 'Tahrirlash',
    'delete_btn2': "O'chirish",
    'permissions_btn': 'Ruxsatlar',
    'promote_btn': 'Promote',
    'demote_btn': 'Demote',
    'make_admin_btn': 'Admin qilish',
    'all_restaurants': 'Barcha restoranlar',
    'all_statuses': 'Barcha statuslar',
    'clear_btn': 'Tozalash',
    'delete_all_btn': "Hammasini o'chirish",
    'no_orders_found': 'Zakazlar topilmadi.',
    'system_info': "Tizim ma'lumotlari",
    'security_section': 'Xavfsizlik',
    'danger_zone': 'Xavfli zona',
    'change_password_btn': "Parolni o'zgartirish",
    'delete_all_orders': 'Barcha zakazlarni o\'chirish',
    'sign_out_btn': 'Tizimdan chiqish',
    'active_status': 'Faol',
    'inactive_status': 'Nofaol',
    'tables_count_label': 'Stollar soni',
    'unique_order_system': 'Stollar uchun unikal buyurtma tizimi',
    'add_item_title2': "Yangi Ovqat Qo'shish",
    'edit_item_title2': 'Ovqatni Tahrirlash',
    'price_label': "Narxi (so'm)",
    'add_category_btn': "Yangi Kategoriya Qo'shish",
    'edit_category_btn': 'Kategoriyani Tahrirlash',
    'restaurant_name_required': 'Restoran nomi majburiy',
    'owner_name_required': 'Egasi ismi majburiy',
    'login_required_msg': 'Login majburiy',
    'interface_lang_label': 'Interfeys tili',
    'security_tip': 'Xavfsizlik maslahati',
    'security_tip_desc': 'Kamida 12 ta belgi, katta va kichik harflar, raqamlar va maxsus belgilar ishlatish tavsiya etiladi.',
    'danger_zone_desc': 'Bu bo\'limdagi amallar qaytarib bo\'lmaydi. Ehtiyot bo\'ling.',
    'dashboard_title': 'Dashboard',
    'system_overview': "Tizim umumiy ko'rinishi",
    'restaurants_count': 'Restoranlar',
    'today_orders': 'Bugungi zakazlar',
    'today_revenue': 'Bugungi daromad',
    'users_count': 'Foydalanuvchilar',
    'total_prefix': 'Jami',
    'time_col': 'Vaqt',
    'user_col': 'Foydalanuvchi',
    'restaurant_table_col': 'Restoran / Stol',
    'total_col': 'Jami',
    'status_col': 'Holat',
    'payment_col': "To'lov",
    'ip_col': 'IP / Joylashuv',
    'actions_col': 'Amallar',
    'owner_col': 'Egasi',
    'contact_col': 'Aloqa',
    'tables_col': 'Stollar',
    'login_col2': 'Login',
    'type_col': 'Turi',
    'ip_address_col': 'IP Manzil',
    'location_col': 'Joylashuv',
    'last_activity_col': 'Oxirgi faollik',
    'login_count_col': 'Kirish soni',
    'device_col': 'Qurilma',
    'browser_col': 'Brauzer',
    'cash_payment': 'Naqd',
    'card_payment': 'Karta',
    'guest_user': 'Mehmon',
    'no_data_yet': 'Hozircha zakazlar yo\'q',
    'no_activity': 'Ma\'lumot yo\'q. Foydalanuvchilar tizimga kirganda bu yerda ko\'rinadi.',
    'order_detail_title': 'Zakaz tafsiloti',
    'activity_detail_title': 'Foydalanuvchi tafsiloti',
    'login_history': 'Kirish tarixi',
    'order_items_title': 'Buyurtma qilingan taomlar',
    'grand_total': 'Jami',
    'standard_admin': 'Standart admin',
    'orders_only': 'Faqat buyurtmalar',
    'extended': 'Kengaytirilgan',
    'dangerous_label': 'Xavfli',
    'allowed': 'Ruxsat',
    'forbidden': 'Taqiq',
    'permissions_warning': 'Tizim vakolatlari xavfli — faqat ishonchli adminlarga bering',
    'for_user': 'uchun vakolatlar',
    'super_admin_label': 'Super Admin',
    'admin_label': 'Admin',
    'user_label': 'Foydalanuvchi',
    'main_super_admin_error': 'Asosiy Super Admin o\'chirib bo\'lmaydi!',
    'csv_export': 'CSV Eksport',
    'search_placeholder2': 'Qidirish: username, IP, mamlakat...',
    'search_orders': 'Qidirish: username, restoran, IP...',
    'clear_all': 'Tozalash',
    'delete_all_confirm': 'Hammasini o\'chirish',
    'receipt_btn': '🧾 Chek',
    'cancel_order_btn': '✕ Bekor',
    'confirm_btn': '✓ Tasdiqlash',
    'prepare_btn': '🍳 Tayyorlash',
    'ready_btn': '✓ Tayyor',
    'serve_btn': '🍽 Berish',
    'complete_btn': '✓ Yakunlash',
    'dine_in_label': 'Dine-in',
    'takeaway_label': 'Takeaway',
    'items_count': 'ta mahsulot',
    'more_items': 'ta ko\'proq',
    'total_items': 'Jami',
    'som_unit': 'so\'m',
    'profile_title': 'Profil',
    'admin_role': 'Admin',
    'super_admin_role': 'Super Admin',
    'menu_section': 'Menyu',
    'management_section': 'Boshqaruv',
    'pending_orders_text': 'ta yangi buyurtma',
    'order_number_prefix': '#',
    'table_number_prefix': 'Stol',
    'items_ta': 'ta',
    'order_management_title': 'Jonli navbat boshqaruvi',
    'refreshing_text': 'Yangilanmoqda...',
    'refresh_text': 'Yangilash',
    'no_orders_empty': 'Hozircha buyurtmalar yo\'q',
    'orders_appear_text': 'Mijozlar buyurtma berganida bu yerda ko\'rinadi',
  },
  ru: {
    'refreshing_btn': 'Обновляется...',
    'refresh_btn': 'Обновить',
    'saving_btn': 'Сохраняется...',
    'save_btn': 'Сохранить',
    'submitting': 'Отправляется...',
    'cancel_btn': 'Отмена',
    'add_btn': 'Добавить',
    'edit_btn': 'Редактировать',
    'delete_btn': 'Удалить',
    'new_orders_badge': 'новых заказов',
    'live_data': 'Данные в реальном времени',
    'pending_status': 'В очереди',
    'table_prefix': 'Стол',
    'som': 'сум',
    'minute_short': 'мин',
    'scanner_btn': 'Сканер',
    'system_control': 'Управление системой',
    'total_active': 'Всего активных',
    'admins_count': 'Администраторы',
    'last_7_days': 'Последние 7 дней — Заказы',
    'new_restaurant_btn': 'Новый ресторан',
    'edit_btn2': 'Редактировать',
    'delete_btn2': 'Удалить',
    'permissions_btn': 'Права',
    'promote_btn': 'Повысить',
    'demote_btn': 'Понизить',
    'make_admin_btn': 'Сделать админом',
    'all_restaurants': 'Все рестораны',
    'all_statuses': 'Все статусы',
    'clear_btn': 'Очистить',
    'delete_all_btn': 'Удалить все',
    'no_orders_found': 'Заказы не найдены.',
    'system_info': 'Информация о системе',
    'security_section': 'Безопасность',
    'danger_zone': 'Опасная зона',
    'change_password_btn': 'Изменить пароль',
    'delete_all_orders': 'Удалить все заказы',
    'sign_out_btn': 'Выйти из системы',
    'active_status': 'Активен',
    'inactive_status': 'Неактивен',
    'tables_count_label': 'Количество столов',
    'unique_order_system': 'Уникальная система заказов для столов',
    'add_item_title2': 'Добавить новое блюдо',
    'edit_item_title2': 'Редактировать блюдо',
    'price_label': 'Цена (сум)',
    'add_category_btn': 'Добавить новую категорию',
    'edit_category_btn': 'Редактировать категорию',
    'restaurant_name_required': 'Название ресторана обязательно',
    'owner_name_required': 'Имя владельца обязательно',
    'login_required_msg': 'Логин обязателен',
    'interface_lang_label': 'Язык интерфейса',
    'security_tip': 'Совет по безопасности',
    'security_tip_desc': 'Рекомендуется использовать минимум 12 символов, заглавные и строчные буквы, цифры и специальные символы.',
    'danger_zone_desc': 'Действия в этом разделе нельзя отменить. Будьте осторожны.',
    'dashboard_title': 'Дашборд',
    'system_overview': 'Общий вид системы',
    'restaurants_count': 'Рестораны',
    'today_orders': 'Заказы сегодня',
    'today_revenue': 'Выручка сегодня',
    'users_count': 'Пользователи',
    'total_prefix': 'Всего',
    'time_col': 'Время',
    'user_col': 'Пользователь',
    'restaurant_table_col': 'Ресторан / Стол',
    'total_col': 'Итого',
    'status_col': 'Статус',
    'payment_col': 'Оплата',
    'ip_col': 'IP / Местоположение',
    'actions_col': 'Действия',
    'owner_col': 'Владелец',
    'contact_col': 'Контакт',
    'tables_col': 'Столы',
    'login_col2': 'Логин',
    'type_col': 'Тип',
    'ip_address_col': 'IP Адрес',
    'location_col': 'Местоположение',
    'last_activity_col': 'Последняя активность',
    'login_count_col': 'Кол-во входов',
    'device_col': 'Устройство',
    'browser_col': 'Браузер',
    'cash_payment': 'Наличные',
    'card_payment': 'Карта',
    'guest_user': 'Гость',
    'no_data_yet': 'Заказов пока нет',
    'no_activity': 'Нет данных. Здесь будет отображаться активность пользователей.',
    'order_detail_title': 'Детали заказа',
    'activity_detail_title': 'Детали пользователя',
    'login_history': 'История входов',
    'order_items_title': 'Заказанные блюда',
    'grand_total': 'Итого',
    'standard_admin': 'Стандартный админ',
    'orders_only': 'Только заказы',
    'extended': 'Расширенный',
    'dangerous_label': 'Опасно',
    'allowed': 'Разрешено',
    'forbidden': 'Запрещено',
    'permissions_warning': 'Системные права опасны — давайте только доверенным администраторам',
    'for_user': 'права для',
    'super_admin_label': 'Супер Админ',
    'admin_label': 'Админ',
    'user_label': 'Пользователь',
    'main_super_admin_error': 'Главного Супер Админа нельзя удалить!',
    'csv_export': 'CSV Экспорт',
    'search_placeholder2': 'Поиск: username, IP, страна...',
    'search_orders': 'Поиск: username, ресторан, IP...',
    'clear_all': 'Очистить',
    'delete_all_confirm': 'Удалить все',
    'receipt_btn': '🧾 Чек',
    'cancel_order_btn': '✕ Отмена',
    'confirm_btn': '✓ Подтвердить',
    'prepare_btn': '🍳 Готовить',
    'ready_btn': '✓ Готов',
    'serve_btn': '🍽 Подать',
    'complete_btn': '✓ Завершить',
    'dine_in_label': 'В зале',
    'takeaway_label': 'С собой',
    'items_count': 'позиций',
    'more_items': 'ещё',
    'total_items': 'Всего',
    'som_unit': 'сум',
    'profile_title': 'Профиль',
    'admin_role': 'Админ',
    'super_admin_role': 'Супер Админ',
    'menu_section': 'Меню',
    'management_section': 'Управление',
    'pending_orders_text': 'новых заказов',
    'order_number_prefix': '#',
    'table_number_prefix': 'Стол',
    'items_ta': 'шт',
    'order_management_title': 'Управление очередью в реальном времени',
    'refreshing_text': 'Обновляется...',
    'refresh_text': 'Обновить',
    'no_orders_empty': 'Заказов пока нет',
    'orders_appear_text': 'Заказы появятся здесь когда клиенты сделают заказ',
  },
  en: {
    'refreshing_btn': 'Refreshing...',
    'refresh_btn': 'Refresh',
    'saving_btn': 'Saving...',
    'save_btn': 'Save',
    'submitting': 'Submitting...',
    'cancel_btn': 'Cancel',
    'add_btn': 'Add',
    'edit_btn': 'Edit',
    'delete_btn': 'Delete',
    'new_orders_badge': 'new orders',
    'live_data': 'Live data',
    'pending_status': 'In queue',
    'table_prefix': 'Table',
    'som': 'sum',
    'minute_short': 'min',
    'scanner_btn': 'Scanner',
    'system_control': 'System management',
    'total_active': 'Total active',
    'admins_count': 'Admins',
    'last_7_days': 'Last 7 days — Orders',
    'new_restaurant_btn': 'New Restaurant',
    'edit_btn2': 'Edit',
    'delete_btn2': 'Delete',
    'permissions_btn': 'Permissions',
    'promote_btn': 'Promote',
    'demote_btn': 'Demote',
    'make_admin_btn': 'Make admin',
    'all_restaurants': 'All restaurants',
    'all_statuses': 'All statuses',
    'clear_btn': 'Clear',
    'delete_all_btn': 'Delete all',
    'no_orders_found': 'No orders found.',
    'system_info': 'System information',
    'security_section': 'Security',
    'danger_zone': 'Danger zone',
    'change_password_btn': 'Change password',
    'delete_all_orders': 'Delete all orders',
    'sign_out_btn': 'Sign out',
    'active_status': 'Active',
    'inactive_status': 'Inactive',
    'tables_count_label': 'Number of tables',
    'unique_order_system': 'Unique ordering system for tables',
    'add_item_title2': 'Add New Item',
    'edit_item_title2': 'Edit Item',
    'price_label': 'Price (sum)',
    'add_category_btn': 'Add New Category',
    'edit_category_btn': 'Edit Category',
    'restaurant_name_required': 'Restaurant name is required',
    'owner_name_required': 'Owner name is required',
    'login_required_msg': 'Login is required',
    'interface_lang_label': 'Interface language',
    'security_tip': 'Security tip',
    'security_tip_desc': 'It is recommended to use at least 12 characters, uppercase and lowercase letters, numbers and special characters.',
    'danger_zone_desc': 'Actions in this section cannot be undone. Be careful.',
    'dashboard_title': 'Dashboard',
    'system_overview': 'System overview',
    'restaurants_count': 'Restaurants',
    'today_orders': 'Today\'s orders',
    'today_revenue': 'Today\'s revenue',
    'users_count': 'Users',
    'total_prefix': 'Total',
    'time_col': 'Time',
    'user_col': 'User',
    'restaurant_table_col': 'Restaurant / Table',
    'total_col': 'Total',
    'status_col': 'Status',
    'payment_col': 'Payment',
    'ip_col': 'IP / Location',
    'actions_col': 'Actions',
    'owner_col': 'Owner',
    'contact_col': 'Contact',
    'tables_col': 'Tables',
    'login_col2': 'Login',
    'type_col': 'Type',
    'ip_address_col': 'IP Address',
    'location_col': 'Location',
    'last_activity_col': 'Last activity',
    'login_count_col': 'Login count',
    'device_col': 'Device',
    'browser_col': 'Browser',
    'cash_payment': 'Cash',
    'card_payment': 'Card',
    'guest_user': 'Guest',
    'no_data_yet': 'No orders yet',
    'no_activity': 'No data. User activity will appear here when they log in.',
    'order_detail_title': 'Order details',
    'activity_detail_title': 'User details',
    'login_history': 'Login history',
    'order_items_title': 'Ordered items',
    'grand_total': 'Total',
    'standard_admin': 'Standard admin',
    'orders_only': 'Orders only',
    'extended': 'Extended',
    'dangerous_label': 'Dangerous',
    'allowed': 'Allowed',
    'forbidden': 'Forbidden',
    'permissions_warning': 'System permissions are dangerous — only give to trusted admins',
    'for_user': 'permissions for',
    'super_admin_label': 'Super Admin',
    'admin_label': 'Admin',
    'user_label': 'User',
    'main_super_admin_error': 'Main Super Admin cannot be deleted!',
    'csv_export': 'CSV Export',
    'search_placeholder2': 'Search: username, IP, country...',
    'search_orders': 'Search: username, restaurant, IP...',
    'clear_all': 'Clear',
    'delete_all_confirm': 'Delete all',
    'receipt_btn': '🧾 Receipt',
    'cancel_order_btn': '✕ Cancel',
    'confirm_btn': '✓ Confirm',
    'prepare_btn': '🍳 Prepare',
    'ready_btn': '✓ Ready',
    'serve_btn': '🍽 Serve',
    'complete_btn': '✓ Complete',
    'dine_in_label': 'Dine-in',
    'takeaway_label': 'Takeaway',
    'items_count': 'items',
    'more_items': 'more',
    'total_items': 'Total',
    'som_unit': 'sum',
    'profile_title': 'Profile',
    'admin_role': 'Admin',
    'super_admin_role': 'Super Admin',
    'menu_section': 'Menu',
    'management_section': 'Management',
    'pending_orders_text': 'new orders',
    'order_number_prefix': '#',
    'table_number_prefix': 'Table',
    'items_ta': 'pcs',
    'order_management_title': 'Live queue management',
    'refreshing_text': 'Refreshing...',
    'refresh_text': 'Refresh',
    'no_orders_empty': 'No orders yet',
    'orders_appear_text': 'Orders will appear here when customers place them',
  },
};

Object.keys(adminTranslations).forEach((lang) => {
  const l = lang as 'uz' | 'ru' | 'en';
  Object.assign(translations[l], adminTranslations[l]);
});

// ── Waiter call translations ─────────────────────────────────────────────
const waiterTranslations: Record<'uz' | 'ru' | 'en', Record<string, string>> = {
  uz: {
    'call_waiter': 'Ofitsiant chaqirish',
    'call_waiter_btn': '🛎️ Ofitsiant chaqirish',
    'waiter_calling': 'Chaqirilmoqda...',
    'waiter_called': 'Ofitsiant kelmoqda...',
    'waiter_called_toast': 'Ofitsiant chaqirildi! Tez orada keladi 🛎️',
    'waiter_call_desc': 'Yordam kerak bo\'lsa ofitsiantni chaqiring',
    'waiter_badge': 'stol ofitsiant chaqirmoqda',
    'waiter_dismiss': 'Bosib o\'chirish',
  },
  ru: {
    'call_waiter': 'Вызвать официанта',
    'call_waiter_btn': '🛎️ Вызвать официанта',
    'waiter_calling': 'Вызывается...',
    'waiter_called': 'Официант идёт...',
    'waiter_called_toast': 'Официант вызван! Скоро придёт 🛎️',
    'waiter_call_desc': 'Вызовите официанта если нужна помощь',
    'waiter_badge': 'стол вызывает официанта',
    'waiter_dismiss': 'Нажмите чтобы убрать',
  },
  en: {
    'call_waiter': 'Call Waiter',
    'call_waiter_btn': '🛎️ Call Waiter',
    'waiter_calling': 'Calling...',
    'waiter_called': 'Waiter is coming...',
    'waiter_called_toast': 'Waiter called! Coming soon 🛎️',
    'waiter_call_desc': 'Call a waiter if you need help',
    'waiter_badge': 'table calling waiter',
    'waiter_dismiss': 'Click to dismiss',
  },
};

Object.keys(waiterTranslations).forEach((lang) => {
  const l = lang as 'uz' | 'ru' | 'en';
  Object.assign(translations[l], waiterTranslations[l]);
});

// ── Menu extra translations ──────────────────────────────────────────────
const menuExtraTranslations: Record<'uz' | 'ru' | 'en', Record<string, string>> = {
  uz: {
    'my_orders': 'Buyurtmam',
    'product': 'mahsulot',
    'new_cart': 'Yangi restoran — savat tozalandi',
  },
  ru: {
    'my_orders': 'Мои заказы',
    'product': 'позиций',
    'new_cart': 'Новый ресторан — корзина очищена',
  },
  en: {
    'my_orders': 'My Orders',
    'product': 'items',
    'new_cart': 'New restaurant — cart cleared',
  },
};

Object.keys(menuExtraTranslations).forEach((lang) => {
  const l = lang as 'uz' | 'ru' | 'en';
  Object.assign(translations[l], menuExtraTranslations[l]);
});

// ── Cart extra translations ──────────────────────────────────────────────
const cartExtraTranslations: Record<'uz' | 'ru' | 'en', Record<string, string>> = {
  uz: {
    'order_type': 'Buyurtma turi',
    'session_expired_scan': 'Sessiya muddati tugagan. QR kodni qayta skanerlang.',
    'scan_qr_first': 'Buyurtma berish uchun avval QR kodni skanerlang!',
    'deleted': "O'chirildi",
    'order_placed': 'Buyurtma muvaffaqiyatli berildi!',
  },
  ru: {
    'order_type': 'Тип заказа',
    'session_expired_scan': 'Сессия истекла. Отсканируйте QR код заново.',
    'scan_qr_first': 'Для заказа сначала отсканируйте QR код!',
    'deleted': 'Удалено',
    'order_placed': 'Заказ успешно оформлен!',
  },
  en: {
    'order_type': 'Order type',
    'session_expired_scan': 'Session expired. Please scan QR code again.',
    'scan_qr_first': 'Please scan QR code first to place an order!',
    'deleted': 'Removed',
    'order_placed': 'Order placed successfully!',
  },
};

Object.keys(cartExtraTranslations).forEach((lang) => {
  const l = lang as 'uz' | 'ru' | 'en';
  Object.assign(translations[l], cartExtraTranslations[l]);
});
